
# project name
name: 'snowflake_dbt_python_formula1'
version: '1.3.0'
require-dbt-version: '>=1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
 - "target"
 - "dbt_packages"

models:
 snowflake_dbt_python_formula1:
   staging:

 +docs:
   node_color: "CadetBlue"
marts:
 +materialized: table #Note: Python models can only be materialized as tables or incremental models
 aggregates:
   +docs:
     node_color: "Maroon"
   +tags: "bi"

 core:
   +docs:
     node_color: "#800080"
 intermediate:
   +docs:
     node_color: "MediumSlateBlue"
 ml:
   prep:
     +docs:
       node_color: "Indigo"
   train_predict:
     +docs:
       node_color: "#36454f"
